services:
  api:
    build:
      context: ./api
      dockerfile: breezy_api.Dockerfile
    container_name: node-api
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017/breezy_bdd
    depends_on:
      - mongo
    volumes:
      - ./api:/app
      - node_modules_api:/app/node_modules

  mongo:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_URI=mongodb://mongo:27017/breezy_bdd
    volumes:
      - mongo_data:/data/db
      - ./api/Database/init_bdd.js:/docker-entrypoint-initdb.d/init_bdd.js:ro

volumes:
  mongo_data:
  node_modules_api: