services:
  api:
    build:
      context: ./api
      dockerfile: breezy_api.Dockerfile
    container_name: node-api
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/breezy_bdd
    depends_on:
      - mongodb
    volumes:
      - ./api:/app
      - node_modules_api:/app/node_modules
    networks:
      - backend
    command: ["./wait-for-it.sh", "mongodb", "27017", "npm", "start"]

  mongodb:
    build:
      context: ./Database
      dockerfile: mongodb.Dockerfile
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/breezy_bdd
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

volumes:
  mongo_data:
  node_modules_api:

networks:
  backend: