name: Test File Server

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths:
      - "FileServer/**"
      - ".github/workflows/test_file_server.yml"
  pull_request:
    branches:
      - "**"
    paths:
      - "FileServer/**"

jobs:
  test-file-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check Docker and Docker Compose versions
        run: |
          docker --version
          docker compose version

      - name: Build and Start File Server
        run: docker compose up -d --build fileserver

      - name: Show memory usage before test
        run: free -h

      - name: Run File Server tests
        id: test
        run: |
          set +e
          docker compose exec -T fileserver npm run test --trace-warning
          CODE=$?
          echo "exit_code=$CODE" >> $GITHUB_OUTPUT
          if [ $CODE -eq 137 ]; then
            echo "::error::Tests failed with exit code 137 (out of memory). Consider optimizing your tests or increasing available memory."
            exit 1
          fi
          exit $CODE

      - name: Show memory usage after test
        run: free -h

      - name: Tear down
        if: always()
        run: |
          docker compose down --volumes
          docker system prune -a -f