name: Test API

on:
  workflow_dispatch:
  push:
    branches:
        - "**"
    paths:
      - "api/**"
      - "Database/**"
      - ".github/workflows/test-api.yml"
  pull_request:
    branches:
        - "**"
    paths:
      - "api/**"
      - "Database/**"

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and Start API + MongoDB
        run: docker-compose up -d --build mongodb api

      - name: Run API tests
        run: docker-compose exec -T node-api npm test

      - name: Tear down
        if: always()
        run: docker-compose down --volumes