name: Test API

on:
  workflow_dispatch:
  push:
    branches:
        - "**"
    paths:
      - "API/**"
      - "Database/**"
      - "docker-compose.yml"
      - ".github/workflows/test_api.yml"
  pull_request:
    branches:
        - "**"
    paths:
      - "API/**"
      - "Database/**"
      - "docker-compose.yml"

jobs:
  test-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check Docker and Docker Compose versions
        run: |
          docker --version
          docker compose version

      - name: Build and Start API
        run: docker compose up -d --build api

      - name: Show memory usage before test
        run: docker compose exec -T api free -h

      - name: Run API tests
        run: docker compose exec -T api ./wait-for-it.sh mongodb 27017 npm run test --trace-warning

      - name: Show memory usage after test
        run: docker compose exec -T api free -h

      - name: Tear down
        if: always()
        run: |
          docker compose down --volumes
          docker system prune -a