name: Test API

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths:
      - "API/**"
      - "Database/**"
      - ".github/workflows/test_api.yml"
  pull_request:
    branches:
      - "**"
    paths:
      - "API/**"
      - "Database/**"

jobs:
  test-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check Docker and Docker Compose versions
        run: |
          docker --version
          docker compose version

      - name: Build and Start API + MongoDB
        run: docker compose up -d --build mongodb api

      - name: Wait for MongoDB to be ready
        run: docker compose exec -T api ./wait-for-it.sh mongodb:27017 --timeout=30 --strict -- echo "MongoDB is up"

      - name: Show memory usage before test
        run: free -h

      - name: Run API tests
        run: docker compose exec -T api npm run test --trace-warning

      - name: Show memory usage after test
        run: free -h

      - name: Tear down
        if: always()
        run: |
          docker compose down --volumes
          docker system prune -a -f