name: Test API

on:
  workflow_dispatch:
  push:
    branches:
        - "**"
    paths:
      - "API/**"
      - "Database/**"
      - ".github/workflows/test_api.yml"
  pull_request:
    branches:
        - "**"
    paths:
      - "API/**"
      - "Database/**"

jobs:
  test-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check Docker and Docker Compose versions
        run: |
          docker --version
          docker compose version

      - name: Build and Start API + MongoDB
        run: docker compose up -d --build mongodb api

      - name: Run API tests
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
        run: docker compose exec -T api ./wait-for-it.sh mongodb 27017 npm run test --trace-warning
=======
        run: docker compose exec -T api ./wait-for-it.sh mongodb 27017 npm run test
>>>>>>> 9957fd7 (feat : tentatives de fonctionnement de la pipeline pour les tests d'api automatique #39)
=======
        run: docker compose exec -T api ./wait-for-it.sh mongodb 27017 npm run test --trace-warning
>>>>>>> 40b0c8e (feat : réglage tests unitaires sur le serveur de fichier #39 #40)

      - name: Tear down
        if: always()
<<<<<<< HEAD
        run: |
          docker compose down --volumes
          docker system prune -a
=======
        run: docker compose down --volumes
        run: docker system prune -a
>>>>>>> 627c6a4 (feat : finalisation suppression docker compose après lancement des tests #39 #40)
=======
        run: docker compose exec -T api npm run test --trace-warning

      - name: Show memory usage after test
        run: free -h
=======
        run: docker compose exec -T api ./wait-for-it.sh mongodb 27017 npm run test --trace-warning
>>>>>>> 8d85f3f (feat : Test #39 #40)

      - name: Tear down
        if: always()
        run: |
          docker compose down --volumes
<<<<<<< HEAD
          docker system prune -a -f
>>>>>>> 7f900a4 (feat : ajout vérification mémoire utilisée sur chaque test #39 #40)
=======
          docker system prune -a
>>>>>>> 8d85f3f (feat : Test #39 #40)
