name: Test API

on:
  workflow_dispatch:
  push:
    branches:
        - "**"
    paths:
      - "API/**"
      - "Database/**"
      - ".github/workflows/test-api.yml"
  pull_request:
    branches:
        - "**"
    paths:
      - "API/**"
      - "Database/**"

jobs:
  test-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check Docker and Docker Compose versions
        run: |
          docker --version
          docker compose version

      - name: Build and Start API + MongoDB
        run: docker compose up -d --build mongodb api

      - name: Run API tests
        run: docker compose exec -T node-api npm run test

      - name: Tear down
        if: always()
        run: docker compose down --volumes