name: Test File Server

on:
  workflow_dispatch:
  push:
    branches:
        - "**"
    paths:
      - "FileServer/**"
      - ".github/workflows/test_file_server.yml"
  pull_request:
    branches:
        - "**"
    paths:
      - "FileServer/**"

jobs:
  test-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check Docker and Docker Compose versions
        run: |
          docker --version
          docker compose version

      - name: Build and Start File Server
        run: docker compose up -d --build fileserver

      - name: Run File Server tests
        run: docker compose exec -T fileserver npm run test

      - name: Tear down
        if: always()
        run: docker compose down --volumes