name: Test File Server

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths:
      - "FileServer/**"
      - ".github/workflows/test_file_server.yml"
  pull_request:
    branches:
      - "**"
    paths:
      - "FileServer/**"

jobs:
  test-file-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check Docker and Docker Compose versions
        run: |
          docker --version
          docker compose version

      - name: Create minimal docker-compose override (no volume mounts)
        run: |
          cat <<EOF > docker-compose.override.yml
          services:
            fileserver:
              volumes:
                - type: volume
                  source: dummy_volume
                  target: /app/uploads
          volumes:
            dummy_volume:

      - name: Build and Start File Server
        run: docker compose up -d --build fileserver

      - name: Show memory usage before test
        run: free -h

<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
      - name: Run File Server tests
<<<<<<< HEAD
        run: docker compose exec -T fileserver npm run test --trace-warning
=======
      - name: Run File Server Tests
        run: docker compose exec -T fileserver bash -c "free -h && npm run test --trace-warning"
>>>>>>> acb70e5 (feat : débug de l'utilisation de la ram lors du github action #39 #40)
=======
      - name: Run File Server tests
        id: test
        run: docker compose exec -T fileserver npm run test --trace-warning
>>>>>>> 8d85f3f (feat : Test #39 #40)
=======
=======
      - name: Run File Server Tests
>>>>>>> 30c5cf8 (Fix)
        id: test
        run: docker compose exec -T fileserver npm run test --trace-warning

      - name: Show memory usage after test
        run: free -h
>>>>>>> 188b741 (feat : ajout vérification mémoire utilisée sur chaque test #39 #40)

      - name: Show memory usage after test
        run: free -h

      - name: Tear down
        if: always()
        run: |
          docker compose down --volumes
          docker system prune -a -f
